name: apiCarinaTest

on:
#  push:
  #  branches: [ web ]
 #   paths-ignore:
#      - '**/README.md'
  pull_request:
    branches: [ web ]
    paths-ignore:
      - '**/README.md'
  

jobs:
  MavenBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Pull the project into the runner step
        uses: actions/checkout@v3

      - name: Set up JDK 11 step
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      
      - name: Build and run tests step
        run: mvn clean test -Dsuite=api 
        
      - name: Create artifacts directory
        if: success() || failure()
        run: mkdir artifacts && cp -r reports artifacts

      - name: Upload artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: my-artifacts
          path: artifacts
        
